install:
  - cmd: ver
  # - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn -Drat.skip=true -T 2 -Ptravis -DskipTests=true -B -V install

test_script:
  # - mvn test -B 
  - mvn -T 2 -Ptravis test

cache:
  - 'C:\Users\%USERNAME%\.m2\repository'

build: off
