install:
  - cmd: java -version
  # - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn -T 2 -Ptravis -DskipTests=true -B -V install

test_script:
  # - mvn test -B 
  - mvn -T 2 -Ptravis test

cache:
  - '%HOMEPATH%\.m2' 

build: off